image:
  file: .gitpod.Dockerfile

# データベースを作成するファイル database.sql を読み込む
# スキーマを作成するファイル schema.sql を読み込む
# テーブル作成用SQLファイル table.sql を読み込む
# 初期データ initdata.sql を読み込む
# JS 準備
tasks:
  - init: psql -f ./DB/database.sql
       && psql -d techdb -f ./DB/schema.sql
       && psql -d techdb -f ./DB/table.sql
       && psql -d techdb -f ./DB/initdata.sql
       && npm install

# Postgresql extension
vscode:
  extensions:
    - ckolkman.vscode-postgres@1.1.17:804d27cd5e9ff60a8c46a387413e9cbf
